# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='cure',
            field=models.CharField(default='Mule Kickin', max_length=100),
            preserve_default=False,
        ),
    ]
